//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoviesInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr,img{border:0}body,figure{margin:0}.img-thumbnail,.thumbnail{-webkit-transition:all .2s ease-in-out}.breadcrumb,.dropdown-menu,.list-inline,.list-unstyled,.media-list,.nav,.pager{list-style:none}html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],templ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrapcss {
            get {
                return ResourceManager.GetString("bootstrapcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;&quot;&gt; &lt;button class=&quot;btn btn-info btn-xs&quot;&gt;&lt;i class=&quot;fa fa-hashtag&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;{{gen-cat}}&lt;/button&gt; &lt;/span&gt;.
        /// </summary>
        internal static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row well&quot;&gt;&lt;div class=&quot;col-sm-2&quot;&gt;&lt;img class=&quot;img-responsive&quot; src=&quot;poster-imdb-gazlu.jpg&quot; height=&quot;170&quot; width=&quot;119&quot;/&gt;&lt;/div&gt;&lt;div class=&quot;col-sm-10&quot;&gt;&lt;h4 class=&quot;Title&quot;&gt;{{title}}&lt;/h4&gt;&lt;p class=&quot;&quot;&gt;{{plot}}&lt;/p&gt;&lt;span class=&quot;pull-left&quot;&gt;&lt;a class=&quot;btn btn-primary&quot; href=&quot;javascript:;&quot;&gt;&lt;i class=&quot;fa fa-star&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; IMDB Rating:{{rating}}&lt;/a&gt;&lt;/span&gt;&lt;span class=&quot;pull-right&quot;&gt;{{genre}}&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;clearfix&quot;&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt; &lt;meta charset=&quot;utf-8&quot;/&gt; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;/&gt; &lt;title&gt;{{title}}&lt;/title&gt; &lt;style&gt;{{styles}}&lt;/style&gt;&lt;link href=&quot;https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css&quot; rel=&quot;stylesheet&quot;/&gt;&lt;/head&gt;&lt;body&gt; &lt;div class=&quot;navbar navbar-inverse navbar-fixed-top&quot;&gt; &lt;div class=&quot;container&quot;&gt; &lt;div class=&quot;navbar-header&quot;&gt; &lt;button type=&quot;button&quot; class=&quot;navbar-toggle&quot; data-toggle=&quot;collapse&quot; data-target=&quot;.navbar-collapse&quot;&gt; &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt; &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string movietemplate {
            get {
                return ResourceManager.GetString("movietemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .field-validation-error,.validation-summary-errors{color:#b94a48}.field-validation-valid,.validation-summary-valid{display:none}body{padding-top:50px;padding-bottom:20px}.body-content{padding-left:15px;padding-right:15px}input.input-validation-error{border:1px solid #b94a48}input[type=checkbox].input-validation-error{border:0}.ajax-busy-indicator{position:fixed;top:50px;right:15px;background-image:url(/Content/busy_indicator.gif);height:48px;width:48px}.
        /// </summary>
        internal static string templatecss {
            get {
                return ResourceManager.GetString("templatecss", resourceCulture);
            }
        }
    }
}
